### ISSUE TITLE
Ошибка перехода в несуществующее меню при нажатии кнопки “Escape” в главном меню

### ISSUE THREAD

**Issue by VladimirMazin** [X-Jedi-Knight-X/Guide-for-museum#11]
Ситуация:
1.)	Запускаем программу
2.)	Нажимаем кнопку “Escape” на клавиатуре 
Поведение программы:
![4444](https://github.com/user-attachments/assets/6637996c-4f3a-47ab-ab24-ea045af945b2)
Ожидаемое поведение:
![5555](https://github.com/user-attachments/assets/74d38732-ecb1-4f6b-b445-93dab14ba9f9)

**Comment by GenichiOniFy** [comment]
Здравствуйте!

Спасибо за ваш отчет о проблеме с переходом в несуществующее меню при нажатии кнопки "Escape" в главном меню. Мы ценим вашу внимательность к деталям и ваше желание помочь нам улучшить продукт.

Мы уже начали расследование этой проблемы и постараемся как можно скорее найти решение.

**Comment by GenichiOniFy** [comment]
Исправлено
